# Generated by Django 4.0.3 on 2022-04-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
